# Site settings
title: "Eric Clark"
email: eclarkdesigns@gmail.com
description: "Front-End Designer and Developer"
baseurl: "/"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: eclarrrk
github_username:  eclarrrk

# Build settings
markdown: rdiscount